[WIP] InMobi Integration
mopub/mopub-ios-mediation pull request #354
Opened 2021-01-06 16:41 UTC by hmertkahraman

2021-01-06 16:43 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> +    if(!isInMobiSDKInitialized) {
Ideally we'd need an InMobi SDK api method to see if it's initialized or not. We will be calling this method across other adapters too.

2021-01-06 16:44 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
Could you provide us three examples for three cases mentioned in the method description? We will adjust this part accordingly.

2021-01-06 16:47 UTC, hmertkahraman commented on InMobi/InMobiBannerCustomEvent.m
> +    if (!self.bannerAd) {
Could we ask if there's a suggestion towards the error happening here? Or is it an internal InMobi SDK error?

2021-01-08 08:45 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> +    if(!isInMobiSDKInitialized) {
void (^completionBlock)(NSError*) = ^( NSError* _Nullable  error) {
            if (error) {
                isInMobiSDKInitialized = false;
                MPLogInfo(@"SDK Initialization Error - %@", error.description);
            }
            else {
                isInMobiSDKInitialized = true;
                MPLogInfo(@"IM Media SDK successfully initialized");
            }
        };
 [IMSdk initWithAccountID:accountId consentDictionary:gdprConsentObject andCompletionHandler:nil];

2021-01-08 08:46 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> +    if(!isInMobiSDKInitialized) {
Please use the the SDK init completion handler to set the bool isInMobiSDKInitialized

2021-01-08 08:52 UTC, kshtgarg21 commented on InMobi/InMobiBannerCustomEvent.m
> +    if (!self.bannerAd) {
Its internal inmobi error like invalid frame size of invalid placement id etc

2021-01-08 08:59 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
@{IM_MPADAPTER_GDPR_CONSENT_AVAILABLE: @"true",
IM_MPADAPTER_GDPR_CONSENT_IAB: @"SAMPLE_IAB_STRING",
IM_MPADAPTER_GDPR_CONSENT_APPLICABLE: @"1" }

2021-01-08 08:59 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
@{IM_MPADAPTER_GDPR_CONSENT_AVAILABLE: @"false",
IM_MPADAPTER_GDPR_CONSENT_IAB: @"SAMPLE_IAB_STRING",
IM_MPADAPTER_GDPR_CONSENT_APPLICABLE: @"0" }

2021-01-08 09:32 UTC, kshtgarg21 requested changes

2021-01-08 09:32 UTC, kshtgarg21 commented on InMobi/InMobiBannerCustomEvent.m
> +@property (nonatomic, strong) CLLocationManager * locationManager;
Any specific use of this locationManager object? I can see that it is not being used anywhere.

2021-01-08 09:32 UTC, kshtgarg21 commented on InMobi/InMobiInterstitialCustomEvent.m
> +    [self.delegate fullscreenAdAdapter:self didFailToLoadAdWithError:(NSError *)error];
-(void)fullscreenAdAdapter:(MPFullscreenAdAdapter *)adapter didFailToShowAdWithError:(NSError *)error;

Please call the didFailToShowAdWithError delegate call back instead of didFailToLoadAdWithError

2021-01-08 09:32 UTC, kshtgarg21 commented on InMobi/InMobiRewardedCustomEvent.m
> +    [self initializeSdkWithParameters:inMobiParameters];
if placement ID check fails in this method call it will not stop initialisation of rewarded ad further.
Please make this check inline with interstitial adapter or return a bool in this method

2021-01-11 21:29 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
Thanks! Can you please let us know what does this entry expects: `IM_MPADAPTER_GDPR_CONSENT_IAB:@"SAMPLE_IAB_STRING`

2021-01-12 07:00 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
This expects GDPR Consent String as IAB specification.

2021-01-13 13:46 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> +    if (accountId != nil && accountId.length > 0 && ([accountId length] == 32 || [accountId length] == 36)) {
Are these checks for 
```
&& ([accountId length] == 32 || [accountId length] == 36)) {
```
necessary and valid? Or should we remove these checks?

2021-01-24 09:16 UTC, kshtgarg21 commented on InMobi/InMobiBannerCustomEvent.m
> +@property (nonatomic, strong) CLLocationManager * locationManager;
Hey @hmertkahraman , you have resolved these comments, but not pushed any changes?

2021-01-24 09:16 UTC, kshtgarg21 commented on InMobi/InMobiInterstitialCustomEvent.m
> +    [self.delegate fullscreenAdAdapter:self didFailToLoadAdWithError:(NSError *)error];
Hey @hmertkahraman , you have resolved these comments, but not pushed any changes?

2021-01-24 09:17 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> +    if (accountId != nil && accountId.length > 0 && ([accountId length] == 32 || [accountId length] == 36)) {
yes these checks are valid and required.

2021-01-25 20:10 UTC, hmertkahraman commented on InMobi/InMobiBannerCustomEvent.m
> +@property (nonatomic, strong) CLLocationManager * locationManager;
Hi @kshtgarg21,

We created this new PR instead to review all the adapters. Please see:
https://github.com/mopub/mopub-ios-mediation/pull/351

2021-01-26 13:18 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
@kshtgarg21 if we pass `null` to  `IM_MPADAPTER_GDPR_CONSENT_IAB`, and pass other fields properly, would GDPR consent still work properly for InMobi SDK? Our SDK cannot provide IAB String.

2021-01-26 20:33 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
Better not set IM_MPADAPTER_GDPR_CONSENT_IAB key in the dictionary.

2021-01-27 15:08 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
So if we will submit:

```
@{IM_MPADAPTER_GDPR_CONSENT_AVAILABLE: @"true",      // or @"false"
IM_MPADAPTER_GDPR_CONSENT_APPLICABLE: @"1" }            // or @"0"
```

 InMobi will successfully obtain the Consent information and InMobi will bid on AB calls? Without the need of `IM_MPADAPTER_GDPR_CONSENT_IAB` ? This is very important for us to clarify because our SDK cannot provide `IAB_STRING`.

2021-02-23 18:55 UTC, hmertkahraman commented on InMobi/InMobiAdapterConfiguration.m
> ++ (void)setGDPRConsentDictionary:(NSDictionary *)consentDictionary {
Removed GDPR flow per offline conversations

2021-03-01 11:21 UTC, kshtgarg21 requested changes

2021-04-28 15:44 UTC, merged