Ogury - 1.3.5
mopub/mopub-ios-mediation pull request #388
Opened 2021-04-29 14:34 UTC by DamienRivetOgury

# Summary

Add support for **Interstitial**, **Rewarded Video** and **Banner** from **Ogury**.

2021-04-30 18:08 UTC, chauduyphanvu requested changes
need additional nil checks, error handlings, and log messages/event

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    MPRewardedVideoReward *reward = [[MPRewardedVideoReward alloc] initWithCurrencyType:currencyType amount:@(amount)];
`MPReward`

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    }
Nil check for `item` first?

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    [self.delegate fullscreenAdAdapterDidLoadAd:self];
Add log message.

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/OguryBannerCustomEvent.m
> +    self.adUnitId = info[kOguryConfigurationAdUnitId];
Validate ad unit ID and fail if applicable.

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/OguryAdapterConfiguration.m
> +    NSString *assetKey = configuration[OguryConfigurationKeyAssetKey];
Nil check on `configuration`.

2021-04-30 18:08 UTC, chauduyphanvu commented on Ogury/NSError+Ogury.m
> +    switch (oguryError) {
Please move this to the `AdapterConfiguration`. No need for a separate class.

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/NSError+Ogury.m
> +    switch (oguryError) {
Moved in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryAdapterConfiguration.m
> +    NSString *assetKey = configuration[OguryConfigurationKeyAssetKey];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    [self.delegate fullscreenAdAdapterDidLoadAd:self];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    }
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryInterstitialCustomEvent.m
> +    [self.interstitial load];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryInterstitialCustomEvent.m
> +    }
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:13 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +@property (nonatomic, strong) OguryAdsOptinVideo *optinVideo;
Changed in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    [self.optinVideo load];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    return self.optinVideo.isLoaded;
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    }
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    MPRewardedVideoReward *reward = [[MPRewardedVideoReward alloc] initWithCurrencyType:currencyType amount:@(amount)];
Changed in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryAdapterConfiguration.m
> +                                         userInfo:@{NSLocalizedDescriptionKey:@"OguryAdsAssetKeyNotValidError. An error occurred during the initialization of the SDK."}];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryBannerCustomEvent.m
> +        [self.delegate inlineAdAdapter:self didFailToLoadAdWithError:[NSError errorWithCode:MOPUBErrorNoInventory]];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryBannerCustomEvent.m
> +}
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:14 UTC, DamienRivetOgury commented on Ogury/OguryInterstitialCustomEvent.m
> +    return self.interstitial.isLoaded;
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:26 UTC, DamienRivetOgury commented
Hi @chauduyphanvu,

Regarding AdUnitId validation interstitial ads, for some very specific cases we do accept an empty value.

2021-05-03 11:28 UTC, DamienRivetOgury commented on Ogury/OguryBannerCustomEvent.m
> +    self.adUnitId = info[kOguryConfigurationAdUnitId];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:28 UTC, DamienRivetOgury commented on Ogury/OguryRewardedVideoCustomEvent.m
> +    self.adUnitId = info[kOguryConfigurationAdUnitId];
Added in [`e149bb4`](https://github.com/mopub/mopub-ios-mediation/pull/388/commits/e149bb4972c186365974ed36add750fdcca16daa).

2021-05-03 11:28 UTC, DamienRivetOgury commented on Ogury/OguryInterstitialCustomEvent.m
> +    self.adUnitId = info[kOguryConfigurationAdUnitId];
Hi @chauduyphanvu,

Regarding ad unit ID validation interstitial ads (and only for this format), for some very specific cases we do accept an empty value.

2021-05-12 14:22 UTC, DamienRivetOgury commented
Hi @chauduyphanvu, you should be able to clone the fork from our organization. If it's not the case, I'll have a look.

2021-06-03 20:39 UTC, chauduyphanvu commented
Done in https://github.com/mopub/mopub-ios-mediation/commit/da057748d15134d96c99f49e454883ad901dd779. Thanks!

2021-06-03 20:39 UTC, closed without merging