Inmobi Mopub Adapter Advanced Bidding Bug fix
mopub/mopub-ios-mediation pull request #401
Opened 2021-06-11 15:14 UTC by kshtgarg21

2021-06-15 13:43 UTC, chauduyphanvu requested changes

2021-06-15 13:43 UTC, chauduyphanvu commented on InMobi/InMobiInterstitialCustomEvent.m
> +        if ([adMarkup isKindOfClass:[NSString class]]) {
Same as above.

2021-06-15 13:43 UTC, chauduyphanvu commented on InMobi/InMobiBannerCustomEvent.m
> +        if ([adMarkup isKindOfClass:[NSString class]]) {
I'd recommend also checking `adMarkup.length > 0` to be safe, since an empty `adMarkup` is still a String but it's empty and means it shouldn't be used.

2021-06-15 13:43 UTC, chauduyphanvu commented on InMobi/InMobiRewardedVideoCustomEvent.m
> +        if ([adMarkup isKindOfClass:[NSString class]]) {
Same as above.

2021-06-15 13:43 UTC, chauduyphanvu commented on InMobi/InMobiRewardedVideoCustomEvent.m
> +    MPReward* reward = [MPReward unspecifiedReward];
```suggestion
    MPReward *reward = [MPReward unspecifiedReward];
```

2021-06-17 09:09 UTC, kshtgarg21 commented
@chauduyphanvu @p158276  I have done the requested changes please have a look

2021-06-18 03:45 UTC, p158276 approved these changes

2021-06-18 03:46 UTC, p158276 commented
Hi @kshtgarg21 , thanks for the response. The change for this PR has been released in the following commit.
https://github.com/mopub/mopub-ios-mediation/commit/aea5b5ae06b9d3dccfdeaf9e24c8ce851028a478

2021-06-18 03:46 UTC, closed without merging