Inmobi - Mopub GDPR
mopub/mopub-ios-mediation pull request #517
Opened 2021-09-17 07:00 UTC by kshtgarg21

2021-09-17 12:47 UTC, p158276 commented on InMobi/InMobiAdapterConfiguration.m
> +    [InMobiAdapterConfiguration updatePartnerGDPRConsent];
We call the bidding Token everytime when ad request happen.. You don't need to update GDPR here as you already call the updatePartnerGDPRConsent before the ad request.

2021-09-24 14:31 UTC, p158276 requested changes

2021-09-24 14:31 UTC, p158276 commented on InMobi/InMobiAdapterConfiguration.m
> +        [InMobiAdapterConfiguration updatePartnerGDPRConsent];
Disconnect the consent setting from the initialization code and call the consent logic before request to ensure consent is set irrespective of the init changes.

2021-09-28 13:34 UTC, kshtgarg21 commented on InMobi/InMobiAdapterConfiguration.m
> +        [InMobiAdapterConfiguration updatePartnerGDPRConsent];
Inmobi SDK also sends the GDPR consent to multiple other internal services while init is being performed hence added the consent logic here.

We are already calling consent logic before ad request.

2021-09-30 10:02 UTC, p158276 commented
Hi @kshtgarg21 ,
The changes have been reflected in this [commit](https://github.com/mopub/mopub-ios-mediation/commit/2d129d8a17e8e8221ab971ae5bfb59397dab7687) for the release. Close the PR here.

2021-09-30 10:02 UTC, closed without merging